
package by.herzhot.soap.pojos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UqcOrderReferBean", targetNamespace = "http://com.hitachi.sawara/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UqcOrderReferBean {


    /**
     * 
     * @param uqcOrderReferRequest
     * @return
     *     returns sawara.hitachi.com.UqcOrderReferResponse
     */
    @WebMethod(operationName = "UqcOrderReferService")
    @WebResult(name = "UqcOrderReferResponse", targetNamespace = "http://com.hitachi.sawara/")
    @RequestWrapper(localName = "UqcOrderReferService", targetNamespace = "http://com.hitachi.sawara/", className = "sawara.hitachi.com.UqcOrderReferService")
    @ResponseWrapper(localName = "UqcOrderReferServiceResponse", targetNamespace = "http://com.hitachi.sawara/", className = "sawara.hitachi.com.UqcOrderReferServiceResponse")
    public UqcOrderReferResponse uqcOrderReferService(
            @WebParam(name = "UqcOrderReferRequest", targetNamespace = "http://com.hitachi.sawara/")
                    UqcOrderReferRequest uqcOrderReferRequest);

}
