
package by.herzhot.soap.pojos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UqcOrderReferBeanService", targetNamespace = "http://com.hitachi.sawara/", wsdlLocation = "file:/C:/Users/ZeON/UqcOrderReferBeanService.wsdl")
public class UqcOrderReferBeanService
    extends Service
{

    private final static URL UQCORDERREFERBEANSERVICE_WSDL_LOCATION;
    private final static WebServiceException UQCORDERREFERBEANSERVICE_EXCEPTION;
    private final static QName UQCORDERREFERBEANSERVICE_QNAME = new QName("http://com.hitachi.sawara/", "UqcOrderReferBeanService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/ZeON/UqcOrderReferBeanService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UQCORDERREFERBEANSERVICE_WSDL_LOCATION = url;
        UQCORDERREFERBEANSERVICE_EXCEPTION = e;
    }

    public UqcOrderReferBeanService() {
        super(__getWsdlLocation(), UQCORDERREFERBEANSERVICE_QNAME);
    }

    public UqcOrderReferBeanService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UQCORDERREFERBEANSERVICE_QNAME, features);
    }

    public UqcOrderReferBeanService(URL wsdlLocation) {
        super(wsdlLocation, UQCORDERREFERBEANSERVICE_QNAME);
    }

    public UqcOrderReferBeanService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UQCORDERREFERBEANSERVICE_QNAME, features);
    }

    public UqcOrderReferBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UqcOrderReferBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UqcOrderReferBean
     */
    @WebEndpoint(name = "UqcOrderReferBeanPort")
    public UqcOrderReferBean getUqcOrderReferBeanPort() {
        return super.getPort(new QName("http://com.hitachi.sawara/", "UqcOrderReferBeanPort"), UqcOrderReferBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UqcOrderReferBean
     */
    @WebEndpoint(name = "UqcOrderReferBeanPort")
    public UqcOrderReferBean getUqcOrderReferBeanPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com.hitachi.sawara/", "UqcOrderReferBeanPort"), UqcOrderReferBean.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UQCORDERREFERBEANSERVICE_EXCEPTION!= null) {
            throw UQCORDERREFERBEANSERVICE_EXCEPTION;
        }
        return UQCORDERREFERBEANSERVICE_WSDL_LOCATION;
    }

}
